apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seaway-system
subjects:
  - kind: ServiceAccount
    name: seaway-system
    namespace: seaway-system
roleRef:
  kind: ClusterRole
  name: seaway-system-role
  apiGroup: rbac.authorization.k8s.io
