apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ctx.sh/authors: "Seaway Authors"
  ctx.sh/license: "Apache"
  ctx.sh/support: "https://github.com/ctxswitch/seaway/issues"
resources:
  - ../../crd
  - ../../base
  - secret.yaml
patches:
  - path: operator.yaml
    target:
      kind: Deployment
      name: seaway-operator
      namespace: seaway-system
  - path: service.yaml
    target:
      kind: Service
      name: seaway-webhook-service
      namespace: seaway-system