apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-vol
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /app/tmp/data/registry
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
