apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/group: tailscale
    app.kubernetes.io/managed-by: kustomize
