FROM alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    git \
    jq \
    openssh-client \
    python3 \
    py3-pip \
    py3-setuptools \
    py3-wheel \
    rsync \
    tar \
    zip

CMD [ "sleep", "infinity" ]
