apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ctx.sh/authors: "Seaway Authors"
  ctx.sh/license: "Apache"
  ctx.sh/support: "https://github.com/ctxswitch/seaway/issues"
resources:
  - github.com/CrunchyData/postgres-operator/config/crd
  - database.yaml
