---
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="$MINIO_ROOT_USER"
    export MINIO_ROOT_PASSWORD="$MINIO_ROOT_PASSWORD"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
---
apiVersion: v1
stringData:
  CONSOLE_ACCESS_KEY: $SEAWAY_S3_ACCESS_KEY
  CONSOLE_SECRET_KEY: $SEAWAY_S3_SECRET_KEY
kind: Secret
metadata:
  name: seaway-user
  namespace: minio
