apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- creds.yaml
- tenant.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/group: minio-tenant
    app.kubernetes.io/managed-by: kustomize