apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: seaway
  namespace: seaway-system
spec:
  exposeServices:
    minio: true
    console: true
  certConfig:
    commonName: '*.seaway-hl.default.svc.cluster.local'
    dnsNames:
    - seaway-ss-0-{0...2}.seaway-hl.default.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: storage-configuration
  features:
    enableSFTP: false
  credsSecret:
    name: root
  image: quay.io/minio/minio:RELEASE.2024-05-01T01-11-10Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - seaway
          topologyKey: kubernetes.io/hostname
    name: ss-0
    servers: 3
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1789569706"
    volumesPerServer: 2
  requestAutoCert: false
  serviceAccountName: seaway-sa
  users:
  - name: seaway-user
  buckets:
  - name: seaway
