apiVersion: v1
kind: Service
metadata:
  name: seaway
  namespace: registries
spec:
  type: NodePort
  ports:
  - name: api
    port: 5000
    targetPort: 5000
    nodePort: 31555
  selector:
    app: seaway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaway
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaway
  template:
    metadata:
      labels:
        app: seaway
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: seaway-creds
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_REGION
          value: us-east-1
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: http://minio.minio.svc.cluster.local:80
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: seaway
        - name: REGISTRY_STORAGE_S3_ENCRYPT
          value: "false"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "false"
        - name: REGISTRY_STORAGE_S3_CHUNKSIZE
          value: "5242880"
        - name: REGISTRY_STORAGE_S3_ROOTDIRECTORY
          value: /registry
        - name: REGISTRY_STORAGE_S3_FORCEPATHSTYLE
          value: "true"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_STORAGE_REDIRECT_DISABLE
          value: "true"
