---
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: default
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"

---
apiVersion: v1
stringData:
  # LOCALDEV TESTING ONLY: seaway/seaway123
  CONSOLE_ACCESS_KEY: seaway
  CONSOLE_SECRET_KEY: seaway123
  AWS_ACCESS_KEY_ID: seaway
  AWS_SECRET_ACCESS_KEY: seaway123
kind: Secret
metadata:
  name: storage-user
  namespace: default
