apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  operator.min.io/authors: MinIO, Inc.
  operator.min.io/license: AGPLv3
  operator.min.io/support: https://subnet.min.io
resources:
- namespace.yaml
- minio-crd.yaml
- minio.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/group: minio
    app.kubernetes.io/managed-by: kustomize
