---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaway-operator
  namespace: seaway-system
  labels:
    app: seaway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaway-operator
  template:
    metadata:
      labels:
        app: seaway-operator
    spec:
      serviceAccountName: seaway-system
      containers:
        - name: operator
          image: docker.io/ctxsh/seaway:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 9090
            - containerPort: 9443
          volumeMounts:
            - name: tls
              mountPath: "/etc/webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: seaway-webhook-cert
