apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaway
  namespace: seaway-system
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seaway-controller
            port:
              number: 443