on:
  push:
    tags:
      - 'v*'
name: Build and Release
jobs:
  build-and-create-release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: build linux/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: amd64
      - name: build linux/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: arm64
      - name: build darwin/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: arm64
      - name: build darwin/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: amd64
      - name: release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          name: ${{ github.ref.name }}
          tag_name: ${{ github.ref.name }}
          body_path: RELEASE.md
          files: |
            ./dist/sea*.tar.gz
