on:
  push:
    tags:
      - 'v[0-9]+.v[0-9]+.v[0-9]+'
name: Build and Release
jobs:
  build-and-create-release:
    name: release
    runs-on: ubuntu-latest
    steps:
      ###
      ### Build release packages
      ###
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: build linux/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: amd64
      - name: build linux/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: arm64
      - name: build darwin/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: arm64
      - name: build darwin/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: amd64

      ###
      ### Release seactl and seaway binaries
      ###
      - name: release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          name: ${{ github.ref.name }}
          tag_name: ${{ github.ref.name }}
          body_path: RELEASE.md
          files: |
            ./dist/sea*.tar.gz

      ###
      ### Release the seaway controller container
      ###
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ctxsh/seaway
          tags: |
            type=semver,pattern={{version}}
      - name: build and push to dockerhub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ctxsh/seaway:test
          build-args: |
            VERSION=0.0.0-test.1
