on:
  push:
    tags:
      - 'v*'
name: Build and Release
jobs:
  build-and-create-release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: build linux/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: amd64
      - name: build linux/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: linux
          ARCH: arm64
      - name: build darwin/arm64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: arm64
      - name: build darwin/amd64 release artifact
        run: make build-seactl-release
        env:
          SYSTEM: darwin
          ARCH: amd64
      - name: upload linux/amd64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/seactl-linux-amd64.tar.gz
          asset_name: seactl-linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload linux/arm64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/seactl-linux-arm64.tar.gz
          asset_name: seactl-linux-arm64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin/amd64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/seactl-darwin-amd64.tar.gz
          asset_name: seactl-darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin/arm64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/seactl-darwin-arm64.tar.gz
          asset_name: seactl-darwin-arm64.tar.gz
          asset_content_type: application/gzip